In [1]:
import pandas as pd

In [2]:
path = "/Users/skush/CodeX/Stress-Level-Classifier/data/processed/cleaned_survey_responses.csv"

In [3]:
df = pd.read_csv(path)
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [4]:
df.head()

,Age,Gender,Occupation,Device_Type,Work_Productivity_Score,Weekend_Screen_Time_Hours,Daily_Phone_Hours,Sleep_Hours,Social_Media_Hours,Stress_Level,Caffeine_Intake_Cups
0,22,Male,Student,iOS,6,4.0,4.0,7.0,1.5,7,3
1,23,Female,Student,iOS,9,2.5,2.0,7.0,0.5,2,0
2,23,Female,Student;Professional,iOS,6,6.0,4.0,7.5,3.0,4,3
3,23,Male,Student,iOS,6,4.5,3.0,8.0,2.0,5,1
4,24,Female,Student,iOS,10,9.0,7.0,6.5,5.0,7,0

In [5]:
irrelevant_columns = ['Device_Type']

In [6]:
df = df.drop(columns=irrelevant_columns)

In [7]:
df["Gender"] = df["Gender"].str.lower()
df["Occupation"] = df["Occupation"].str.lower()

In [8]:
df["Stressed"] = df["Stress_Level"].apply(lambda x: 1 if x > 5 else 0)

In [9]:
df.head()

,Age,Gender,Occupation,Work_Productivity_Score,Weekend_Screen_Time_Hours,Daily_Phone_Hours,Sleep_Hours,Social_Media_Hours,Stress_Level,Caffeine_Intake_Cups,Stressed
0,22,male,student,6,4.0,4.0,7.0,1.5,7,3,1
1,23,female,student,9,2.5,2.0,7.0,0.5,2,0,0
2,23,female,student;professional,6,6.0,4.0,7.5,3.0,4,3,0
3,23,male,student,6,4.5,3.0,8.0,2.0,5,1,0
4,24,female,student,10,9.0,7.0,6.5,5.0,7,0,1

In [26]:
df["Occupation"] = df["Occupation"].str.split(";")

In [27]:
df = df.explode("Occupation")

In [28]:
df.shape

(59, 11)

In [29]:
df = pd.get_dummies(df)

In [30]:
df.head()

,Age,Work_Productivity_Score,Weekend_Screen_Time_Hours,Daily_Phone_Hours,Sleep_Hours,Social_Media_Hours,Stress_Level,Caffeine_Intake_Cups,Stressed,Gender_female,Gender_male,Occupation_professional,Occupation_student
0,22,6,4.0,4.0,7.0,1.5,7,3,1,False,True,False,True
1,23,9,2.5,2.0,7.0,0.5,2,0,0,True,False,False,True
2,23,6,6.0,4.0,7.5,3.0,4,3,0,True,False,False,True
2,23,6,6.0,4.0,7.5,3.0,4,3,0,True,False,True,False
3,23,6,4.5,3.0,8.0,2.0,5,1,0,False,True,False,True

In [31]:
df.columns

Index(['Age', 'Work_Productivity_Score', 'Weekend_Screen_Time_Hours',
       'Daily_Phone_Hours', 'Sleep_Hours', 'Social_Media_Hours',
       'Stress_Level', 'Caffeine_Intake_Cups', 'Stressed', 'Gender_female',
       'Gender_male', 'Occupation_professional', 'Occupation_student'],
      dtype='object')

In [32]:
df = df.rename(columns={
    'Daily_Phone_Hours' : 'Daily_Screen_Hours', 
    'Caffeine_Intake_Cups' : 'Caffeine_Cups_Per_Day'
})

In [33]:
df.to_csv("/Users/skush/CodeX/Stress-Level-Classifier/data/processed/survey_data_labelled.csv")